services:
  backend:
    user: "1002:1002"
    build:
      context: ./backend
      args:
        - PORT=${PORT}
        - UPLOAD_PATH=${UPLOAD_PATH}
    env_file:
      - .env
    volumes:
      - ${MOUNT_POINT}:${UPLOAD_PATH}
    ports:
      - "${PORT}:${PORT}"
